name: Automatic testing
on: [push]
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}
env:
  OTP_VERSION: "26.2.1"
  REBAR3_VERSION: "3.22.1"

jobs:
  compile:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        with:
          otp-version: "${{ env.OTP_VERSION }}"
          rebar3-version: "${{ env.REBAR3_VERSION }}"
      - name: Fetch workspace from cache
        uses: actions/cache@v3
        id: cached-workspace
        with:
          path: |
            _build/*/*/*
            ebin
          key: workspace-${{ github.ref }}
      - name: Compile
        run: rebar3 as test compile

  xref:
    needs: [compile]
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        with:
          otp-version: "${{ env.OTP_VERSION }}"
          rebar3-version: "${{ env.REBAR3_VERSION }}"
      - name: Fetch workspace from cache
        uses: actions/cache@v3
        id: cached-workspace
        with:
          path: |
            _build/*/*/*
            ebin
          key: workspace-${{ github.ref }}
      - name: Run xref
        run: rebar3 xref

  eunit:
    needs: [compile]
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        with:
          otp-version: "${{ env.OTP_VERSION }}"
          rebar3-version: "${{ env.REBAR3_VERSION }}"
      - name: Fetch workspace from cache
        uses: actions/cache@v3
        id: cached-workspace
        with:
          path: |
           _build/*/*/*
            ebin
          key: workspace-${{ github.ref }}
      - name: Run EUnit tests
        run: rebar3 eunit

  dialyzer:
    needs: [compile]
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        with:
          otp-version: "${{ env.OTP_VERSION }}"
          rebar3-version: "${{ env.REBAR3_VERSION }}"
      - name: Fetch workspace from cache
        uses: actions/cache@v3
        id: cached-workspace
        with:
          path: |
            _build/*/*/*
            ebin
          key: workspace-dialyzer-${{ github.ref }}
          restore-keys:
            workspace-${{ github.ref }}
      - name: Run Dialyzer
        run: rebar3 dialyzer

  test-compilation:
    runs-on: ubuntu-24.04
    name: Erlang/OTP ${{matrix.otp}} / rebar3 ${{matrix.rebar3}}
    strategy:
      matrix:
        otp: ['25.0', '26.2.1']
        rebar3: ['3.22.1']
    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.otp}}
          rebar3-version: ${{matrix.rebar3}}
      - run: rebar3 ct
